export const profiles = [
  {
    id: 1,
    name: 'Dr. Dane',
    description: 'African-American, 35, married, one child, PhD in history, college professor',
    photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622513/Dr_Dame_text_apbb9m.jpg',
    photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622513/Dr_Dane_photo_n6lxbb.jpg'
  },
  { id: 2, name: 'Mrs. Dane', description: 'Caucasian, Jewish, 38, counselor in a mental health clinic', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622513/Mrs_Dane_text_smpybn.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622513/Mrs_Dane_photo_luthla.jpg' },
  { id: 3, name: 'Bobby Dane', description: 'Mixed, Jewish, 10, special education classes, mental disability', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622513/Bobby_Dane_text_ptxtgt.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622513/Bobby_Dane_photo_z10vyt.jpg' },
  { id: 4, name: 'Mrs. Garcia', description: 'Hispanic, 33, 9th grade education, exotic dancer, prostitute', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622512/Mrs_Garcia_text_xpscrg.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622512/Mrs_Garcia_photo_r2bhg4.jpg' },
  { id: 5, name: 'Jean Garcia', description: 'Three weeks old, Hispanic, in good health, and nursing', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622512/Jean_Garcia_test_fnma6i.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622512/Jean_Garcia_photo_dodoix.jpg' },
  { id: 6, name: 'Mrs. Evans', description: 'African-American, 32, teacher, divorced with one child', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622511/Mrs_Evan_text_omspua.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622511/Mrs_Evan_photo_gzqjwf.jpg' },
  { id: 7, name: 'Mary Evans', description: 'African-American, 8, 3rd grade, excellent student', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622511/Mary_Evans_text_aa67xq.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622511/Mary_Evans_photo_krj2lu.jpg' },
  { id: 8, name: 'John Jacobs', description: 'Asian-American, 13, 8th grade, honor student', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622511/John_Jacobs_text_fpgfcg.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622511/John_Jacobs_photo_acjkgu.jpg' },
  { id: 9, name: 'Mr. Newton', description: 'Caucasian, 26, medical school, known to have homosexual tendencies', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622510/Mr_Newton_text_alfyew.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622510/Mr_Newton_photo_z1n8mt.jpg' },
  { id: 10, name: 'Mrs. Clark', description: 'Caucasian, 26, electrical engineering, married, no children', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622513/Mrs_Dane_text_smpybn.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622510/Mrs_Clark_photo_zou7zf.jpg' },
  { id: 11, name: 'Sister Mary Kathleen', description: 'Caucasian Nun, 35, English major', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622511/Sister_Mary_Kathleen_text_j3apqh.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622510/Sister_Mary_Kathleen_photo_mn7bd0.jpg' },
  { id: 12, name: 'Mr. Black', description: 'Caucasian', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622510/Mr_Black_text_q6e09i.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622510/Mr_Black_photo_nbw4wh.jpg' },
  { id: 13, name: 'Miss Harris', description: 'Hispanic, 21, nursing major', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622510/MIss_Harris_test_q0dgzu.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622510/Miss_Harris_photo_z1oamy.jpg' },
  { id: 14, name: 'Father Flanagan', description: 'African-American, 37, priest, active in civil rights activities', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622509/Father_Flanagan_text_vm7sjd.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622509/Father_Flanagan_photo_uhelwk.jpg' },
  { id: 15, name: 'Dr. Lee', description: 'Asian-American, 66, MD, general practitioner, has had two heart attacks', photo_text_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622509/Dr_Lee_text_diaqi2.jpg', photo_photo_url: 'https://res.cloudinary.com/dcb0gkhfv/image/upload/v1743622509/Dr_Lee_photo_b0ksla.jpg' }
];
